include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false
analyzer:
  errors:
    require_trailing_commas: ignore
  exclude:
    - "**/firebase_options*.dart"
    - "build/**"
    - "ios/**"
    - "android/**"
    - "firebase/**"
    - "assets/**"
    - "coverage/**"
    - ".dart_tool/**"
    - "lib/**/*.g.dart"
    - "lib/gen/**"
  plugins:
    - custom_lint
