targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: true
          explicit_to_json: true
          include_if_null: true
      riverpod_generator:
        generate_for:
          exclude:
            - "test/mocks/*.dart"
      slang_build_runner:
        options:
          base_locale: ja
          fallback_strategy: base_locale
          translate_var: i18n
          flat_map: false
          timestamp: false
          statistics: false
          output_directory: lib/gen
          input_directory: lib/i18n

global_options:
  freezed:
    runs_before:
      - json_serializable
