name: kingu_family_photos
description: "Kingu Family Photos"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: 3.10.0-75.1.beta

dependencies:
  adaptive_dialog: ^2.4.2
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  firebase_analytics: ^12.0.0
  firebase_app_check: ^0.4.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_remote_config: ^6.0.0
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^16.1.0
  google_fonts: ^6.3.0
  hooks_riverpod: ^2.6.1
  intl: any
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.1
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  talker: ^4.9.3
  talker_flutter: ^4.9.3
  talker_riverpod_logger: ^4.9.3

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  go_router_builder: ^3.0.0
  json_serializable: ^6.9.5

  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  slang_build_runner: ^4.8.0
  test: any
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
